server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      #     127.0.0.1：表示本机，不能用于连接到虚拟机上的 Redis 服务。要用虚拟机ip地址
      host: 192.168.248.100
      port: 6379
      password: 123456


